/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtrump;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexy
 */
public class DTrump extends javax.swing.JFrame {

    /**
     * Creates new form DTrump
     */
    public DTrump() {
        initComponents();

        Hilo hora = new Hilo(jl_hora);
        Thread proceso = new Thread(hora);
        proceso.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_modificar_empleados = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        direccion_empleado_m = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salario_empleado_m = new javax.swing.JTextField();
        edad_empleado_m = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id_empleado_m = new javax.swing.JTextField();
        nombre_empleado_m = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jd_modificar_material = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        guardar_material = new javax.swing.JButton();
        nombre_material_modificar = new javax.swing.JTextField();
        descripcion_material_modificar = new javax.swing.JTextField();
        marca_material_modificar = new javax.swing.JTextField();
        serie_material_modificar = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre_empleado = new javax.swing.JTextField();
        id_empleado = new javax.swing.JTextField();
        edad_empleado = new javax.swing.JTextField();
        salario_empleado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        direccion_empleado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lista_empleados = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_materiales = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nombre_material = new javax.swing.JTextField();
        descripcion_material = new javax.swing.JTextField();
        marca_material = new javax.swing.JTextField();
        serie_material = new javax.swing.JTextField();
        bt_agregar_material = new javax.swing.JButton();
        bt_modificar_material = new javax.swing.JButton();
        bt_eliminar_material = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jl_hora = new javax.swing.JLabel();
        titulo_cronometro = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        jd_modificar_empleados.setTitle("MODIFICAR EMPLEADOS");

        direccion_empleado_m.setColumns(20);
        direccion_empleado_m.setRows(5);
        jScrollPane2.setViewportView(direccion_empleado_m);

        jLabel6.setText("Direccion");

        jLabel7.setText("Salario");

        jLabel8.setText("Edad");

        jLabel9.setText("ID");

        jLabel10.setText("Nombre");

        jButton4.setText("MODIFICAR");
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modificar_empleadosLayout = new javax.swing.GroupLayout(jd_modificar_empleados.getContentPane());
        jd_modificar_empleados.getContentPane().setLayout(jd_modificar_empleadosLayout);
        jd_modificar_empleadosLayout.setHorizontalGroup(
            jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_empleadosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificar_empleadosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificar_empleadosLayout.createSequentialGroup()
                        .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_modificar_empleadosLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edad_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salario_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_modificar_empleadosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nombre_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificar_empleadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jd_modificar_empleadosLayout.setVerticalGroup(
            jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_empleadosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nombre_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(id_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(edad_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(salario_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jLabel15.setText("Nombre");

        jLabel16.setText("Descripcion");

        jLabel17.setText("Marca");

        jLabel18.setText("Numero de Serie");

        guardar_material.setText("Guardar");
        guardar_material.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                guardar_materialMouseMoved(evt);
            }
        });
        guardar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardar_materialMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modificar_materialLayout = new javax.swing.GroupLayout(jd_modificar_material.getContentPane());
        jd_modificar_material.getContentPane().setLayout(jd_modificar_materialLayout);
        jd_modificar_materialLayout.setHorizontalGroup(
            jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_materialLayout.createSequentialGroup()
                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificar_materialLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_modificar_materialLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(serie_material_modificar))
                            .addGroup(jd_modificar_materialLayout.createSequentialGroup()
                                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(44, 44, 44)
                                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombre_material_modificar)
                                    .addComponent(descripcion_material_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(marca_material_modificar)))))
                    .addGroup(jd_modificar_materialLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(guardar_material)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jd_modificar_materialLayout.setVerticalGroup(
            jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_materialLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nombre_material_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(descripcion_material_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(marca_material_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(serie_material_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(guardar_material)
                .addGap(32, 32, 32))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRUMP TOWER ©");

        jTabbedPane1.setToolTipText("");

        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 23, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 73, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Edad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 113, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Direccion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 216, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Salario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 167, -1, -1));
        jPanel1.add(nombre_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 18, 322, -1));
        jPanel1.add(id_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 63, 110, -1));
        jPanel1.add(edad_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 108, 110, -1));
        jPanel1.add(salario_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 162, 110, -1));

        direccion_empleado.setColumns(20);
        direccion_empleado.setRows(5);
        jScrollPane1.setViewportView(direccion_empleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 216, 404, -1));

        jButton1.setText("AGREGAR");
        jButton1.setToolTipText("Da click para agregar un empleado");
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 349, 139, 64));

        jButton2.setText("MODIFICAR");
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 351, -1, -1));

        jButton3.setText("ELIMINAR");
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 351, -1, -1));

        jPanel1.add(lista_empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 386, 261, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dtrump/Trump.jpg"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 460));

        jTabbedPane1.addTab("Empleados", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_materiales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Marca", "Numero de Serie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla_materiales);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 272, 461, 134));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Nombre");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 29, -1, -1));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Descripcion");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 79, -1, -1));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setText("Marca");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 119, -1, -1));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("Numero de Serie");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 171, -1, -1));
        jPanel2.add(nombre_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 24, 181, -1));
        jPanel2.add(descripcion_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 74, 181, -1));
        jPanel2.add(marca_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 119, 181, -1));
        jPanel2.add(serie_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 166, 181, -1));

        bt_agregar_material.setText("Agregar");
        bt_agregar_material.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_agregar_materialMouseMoved(evt);
            }
        });
        bt_agregar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_materialMouseClicked(evt);
            }
        });
        jPanel2.add(bt_agregar_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 211, -1, -1));

        bt_modificar_material.setText("Modificar");
        bt_modificar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificar_materialMouseClicked(evt);
            }
        });
        jPanel2.add(bt_modificar_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 424, -1, -1));

        bt_eliminar_material.setText("Eliminar");
        bt_eliminar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminar_materialMouseClicked(evt);
            }
        });
        jPanel2.add(bt_eliminar_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 424, -1, -1));

        jLabel19.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(254, 254, 254));
        jLabel19.setText("Catalogo");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 243, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dtrump/Trump.jpg"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 460));

        jTabbedPane1.addTab("Materiales", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Productos", jPanel3);

        jl_hora.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jl_hora.setForeground(new java.awt.Color(214, 27, 58));
        jl_hora.setText("0");

        titulo_cronometro.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        titulo_cronometro.setText("Tiempo total de operacion:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(titulo_cronometro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(176, 176, 176))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jl_hora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulo_cronometro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_hora)
                .addContainerGap(371, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ordenes", jPanel4);

        jButton5.setText("SALIR");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Empleados temp = (Empleados) lista_empleados.getSelectedItem();
        nombre_empleado_m.setText(temp.getNombre());
        id_empleado_m.setText(Integer.toString(temp.getID()));
        edad_empleado_m.setText(Integer.toString(temp.getEdad()));
        salario_empleado_m.setText(Integer.toString(temp.getSalario()));
        direccion_empleado_m.setText(temp.getDireccion());

        jd_modificar_empleados.setModal(true);
        jd_modificar_empleados.pack();
        jd_modificar_empleados.setLocationRelativeTo(this);
        jd_modificar_empleados.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void bt_modificar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificar_materialMouseClicked
        if (tabla_materiales.getSelectedRow() >= 0) {
            jd_modificar_material.pack();
            jd_modificar_material.setModal(true);
            jd_modificar_material.setLocationRelativeTo(this);
            jd_modificar_material.setVisible(true);
        }
    }//GEN-LAST:event_bt_modificar_materialMouseClicked

    private void bt_agregar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_materialMouseClicked

        if (bt_agregar_material.isEnabled()) {
            String nombre, descripcion, marca;
            int id;
            nombre = nombre_material.getText();
            descripcion = descripcion_material.getText();
            marca = marca_material.getText();
            id = Integer.parseInt(serie_material.getText());

            nombre_material.setText("");
            descripcion_material.setText("");
            marca_material.setText("");
            serie_material.setText("");
            boolean repetido = false;
            for (int i = 0; i < catalogo.size(); i++) {
                if ((((Materiales) catalogo.at(i)).nombre).equals(nombre) && (((Materiales) catalogo.at(i)).marca).equals(marca)) {
                    repetido = true;
                }
            }
            if (!repetido) {
                catalogo.push_back(new Materiales(nombre, descripcion, marca, id));
                Pila materiales = new Pila();
                materiales.push(new Materiales(nombre, descripcion, marca, id));
                inventario.push_back(materiales);
                DefaultTableModel a = (DefaultTableModel) tabla_materiales.getModel();
                String[] row = {nombre, descripcion, marca, Integer.toString(id)};
                a.addRow(row);

                JOptionPane.showMessageDialog(this, "Material Agregado");
            } else {
                JOptionPane.showMessageDialog(this, "Ese material ya se encuentra en el catalogo");
            }
        }

    }//GEN-LAST:event_bt_agregar_materialMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (jButton1.isEnabled()) {
            String Nombre, Direccion;
            int ID, Edad, Salario;
            boolean Agregar = true;

            Nombre = nombre_empleado.getText();
            Direccion = direccion_empleado.getText();
            ID = Integer.parseInt(id_empleado.getText());
            Edad = Integer.parseInt(edad_empleado.getText());
            Salario = Integer.parseInt(salario_empleado.getText());

            Empleados nuevo_empleado = new Empleados(Nombre, ID, Edad, Direccion, Salario);
            for (int i = 0; i < lista_empleados.getItemCount(); i++) {
                if (((((Empleados) (lista_empleados.getItemAt(i))).getNombre()).toLowerCase()).equals(Nombre.toLowerCase())) {
                    Agregar = false;
                }
            }

            if (Agregar) {
                empleados.Queue(nuevo_empleado);
                lista_empleados.addItem(nuevo_empleado);
                lista_empleados_temp.push_back(nuevo_empleado);
                
                JOptionPane.showMessageDialog(this, "Ha agregado un empleado",
                        "AGREGAR EMPLEADOS", JOptionPane.INFORMATION_MESSAGE);

                nombre_empleado.setText("");
                direccion_empleado.setText("");
                id_empleado.setText("");
                edad_empleado.setText("");
                salario_empleado.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Esta agregando un empleado ya existente",
                        "AGREGAR EMPLEADOS", JOptionPane.INFORMATION_MESSAGE);

                nombre_empleado.setText("");
            }

        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        if ((nombre_empleado.getText()).equals("") || (id_empleado.getText()).equals("")
                || (edad_empleado.getText()).equals("") || (salario_empleado.getText()).equals("")
                || (direccion_empleado.getText()).equals("")) {

            jButton1.setEnabled(false);
        } else {
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1MouseMoved

    private void bt_agregar_materialMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_materialMouseMoved
        if ((nombre_material.getText()).equals("") || (descripcion_material.getText()).equals("")
                || (serie_material.getText()).equals("") || (marca_material.getText()).equals("")) {

            bt_agregar_material.setEnabled(false);
        } else {
            bt_agregar_material.setEnabled(true);
        }
    }//GEN-LAST:event_bt_agregar_materialMouseMoved

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved
        // TODO add your handling code here:
        if ((nombre_empleado_m.getText()).equals("") || (id_empleado_m.getText()).equals("")
                || (edad_empleado_m.getText()).equals("") || (salario_empleado_m.getText()).equals("")
                || (direccion_empleado_m.getText()).equals("")) {

            jButton4.setEnabled(false);
        } else {
            jButton4.setEnabled(true);
        }
    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        if (jButton4.isEnabled()) {
            Empleados temp = (Empleados) lista_empleados.getSelectedItem();

            temp.setNombre(nombre_empleado_m.getText());
            temp.setID(Integer.parseInt(id_empleado_m.getText()));
            temp.setEdad(Integer.parseInt(edad_empleado_m.getText()));
            temp.setSalario(Integer.parseInt(salario_empleado_m.getText()));
            temp.setDireccion(direccion_empleado_m.getText());

            nombre_empleado_m.setText("");
            id_empleado_m.setText("");
            edad_empleado_m.setText("");
            salario_empleado_m.setText("");
            direccion_empleado_m.setText("");

            jd_modificar_empleados.setVisible(false);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        // TODO add your handling code here:
        if (lista_empleados.getItemCount() == 0) {
            jButton2.setEnabled(false);
        } else {
            jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        // TODO add your handling code here:
        if (lista_empleados.getItemCount() == 0) {
            jButton3.setEnabled(false);
        } else {
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        lista_empleados_temp.erase(lista_empleados.getSelectedIndex());
        lista_empleados.removeAllItems();

        while (empleados.GetSize() != 0) {
            empleados.DeQueue();
        }

        for (int i = 0; i < lista_empleados_temp.size(); i++) {
            lista_empleados.addItem(lista_empleados_temp.at(i));
        }
        for (int i = 0; i < lista_empleados_temp.size(); i++) {
            empleados.Queue((Empleados) lista_empleados_temp.at(i));
        }


    }//GEN-LAST:event_jButton3MouseClicked

    private void bt_eliminar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminar_materialMouseClicked
        if (tabla_materiales.getSelectedRow() >= 0) {
            DefaultTableModel m = (DefaultTableModel) tabla_materiales.getModel();
            m.removeRow(tabla_materiales.getSelectedRow());
            catalogo.erase(tabla_materiales.getSelectedRow());
            inventario.erase(tabla_materiales.getSelectedRow());
            for (int i = 0; i < catalogo.size(); i++) {
                System.out.println(((Materiales)catalogo.at(i)).getNombre());
            }
            tabla_materiales.setModel(m);
            System.out.println(catalogo.size());
            System.out.println(inventario.size());
        }
    }//GEN-LAST:event_bt_eliminar_materialMouseClicked

    private void guardar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardar_materialMouseClicked
        String nombre,descripcion,marca;
        int serie,posicion;
        posicion = tabla_materiales.getSelectedRow();
        nombre =nombre_material_modificar.getText();
        descripcion = descripcion_material_modificar.getText();
        marca = marca_material_modificar.getText();
        serie=Integer.parseInt(serie_material_modificar.getText());
        ((Materiales)catalogo.at(posicion)).setNombre(nombre);
        ((Materiales)catalogo.at(posicion)).setMarca(marca);
        ((Materiales)catalogo.at(posicion)).setID(serie);
        ((Materiales)catalogo.at(posicion)).setDescripcion(descripcion);
        ((Pila)(inventario.at(posicion))).modificar(nombre, descripcion, marca, serie);
        DefaultTableModel m = (DefaultTableModel)tabla_materiales.getModel();
        
        for (int i = 0; i < catalogo.size(); i++) {
            m.removeRow(0);
        }
        for (int i = 0; i < catalogo.size(); i++) {
            String[] row = {((Materiales)catalogo.at(i)).getNombre(),((Materiales)catalogo.at(i)).getDescripcion(),
            ((Materiales)catalogo.at(i)).getMarca(),Integer.toString(((Materiales)catalogo.at(i)).getID())};
            m.addRow(row);
        }
        jd_modificar_material.setVisible(false);
        nombre_material_modificar.setText("");
        descripcion_material_modificar.setText("");
        marca_material_modificar.setText("");
        serie_material_modificar.setText("");
    }//GEN-LAST:event_guardar_materialMouseClicked

    private void guardar_materialMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardar_materialMouseMoved
        if ((nombre_material_modificar.getText()).equals("") || (descripcion_material_modificar.getText()).equals("")
                || (serie_material_modificar.getText()).equals("") || (marca_material_modificar.getText()).equals("")) {

            guardar_material.setEnabled(false);
        } else {
            guardar_material.setEnabled(true);
        }
    }//GEN-LAST:event_guardar_materialMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DTrump.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DTrump.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DTrump.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DTrump.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DTrump().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregar_material;
    private javax.swing.JButton bt_eliminar_material;
    private javax.swing.JButton bt_modificar_material;
    private javax.swing.JTextField descripcion_material;
    private javax.swing.JTextField descripcion_material_modificar;
    private javax.swing.JTextArea direccion_empleado;
    private javax.swing.JTextArea direccion_empleado_m;
    private javax.swing.JTextField edad_empleado;
    private javax.swing.JTextField edad_empleado_m;
    private javax.swing.JButton guardar_material;
    private javax.swing.JTextField id_empleado;
    private javax.swing.JTextField id_empleado_m;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jd_modificar_empleados;
    private javax.swing.JDialog jd_modificar_material;
    private javax.swing.JLabel jl_hora;
    private javax.swing.JComboBox<Object> lista_empleados;
    private javax.swing.JTextField marca_material;
    private javax.swing.JTextField marca_material_modificar;
    private javax.swing.JTextField nombre_empleado;
    private javax.swing.JTextField nombre_empleado_m;
    private javax.swing.JTextField nombre_material;
    private javax.swing.JTextField nombre_material_modificar;
    private javax.swing.JTextField salario_empleado;
    private javax.swing.JTextField salario_empleado_m;
    private javax.swing.JTextField serie_material;
    private javax.swing.JTextField serie_material_modificar;
    private javax.swing.JTable tabla_materiales;
    private javax.swing.JLabel titulo_cronometro;
    // End of variables declaration//GEN-END:variables
    Lista catalogo = new Lista();
    Lista inventario = new Lista();
    Cola_Empleados empleados = new Cola_Empleados();
    Lista lista_empleados_temp = new Lista();
}
