/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtrump;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexy
 */
public class DTrump extends javax.swing.JFrame {

    /**
     * Creates new form DTrump
     */
    public DTrump() {
        initComponents();

        HiloHora hora = new HiloHora(jl_hora);
        Thread proceso = new Thread(hora);
        proceso.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_modificar_empleados = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        direccion_empleado_m = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salario_empleado_m = new javax.swing.JTextField();
        edad_empleado_m = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id_empleado_m = new javax.swing.JTextField();
        nombre_empleado_m = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jd_modificar_material = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        guardar_material = new javax.swing.JButton();
        nombre_material_modificar = new javax.swing.JTextField();
        descripcion_material_modificar = new javax.swing.JTextField();
        marca_material_modificar = new javax.swing.JTextField();
        serie_material_modificar = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre_empleado = new javax.swing.JTextField();
        id_empleado = new javax.swing.JTextField();
        edad_empleado = new javax.swing.JTextField();
        salario_empleado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        direccion_empleado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lista_empleados = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_materiales = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nombre_material = new javax.swing.JTextField();
        descripcion_material = new javax.swing.JTextField();
        marca_material = new javax.swing.JTextField();
        serie_material = new javax.swing.JTextField();
        bt_agregar_material = new javax.swing.JButton();
        bt_modificar_material = new javax.swing.JButton();
        bt_eliminar_material = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jl_hora = new javax.swing.JLabel();
        titulo_cronometro = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        jd_modificar_empleados.setTitle("MODIFICAR EMPLEADOS");

        direccion_empleado_m.setColumns(20);
        direccion_empleado_m.setRows(5);
        jScrollPane2.setViewportView(direccion_empleado_m);

        jLabel6.setText("Direccion");

        jLabel7.setText("Salario");

        jLabel8.setText("Edad");

        jLabel9.setText("ID");

        jLabel10.setText("Nombre");

        jButton4.setText("MODIFICAR");
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modificar_empleadosLayout = new javax.swing.GroupLayout(jd_modificar_empleados.getContentPane());
        jd_modificar_empleados.getContentPane().setLayout(jd_modificar_empleadosLayout);
        jd_modificar_empleadosLayout.setHorizontalGroup(
            jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_empleadosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificar_empleadosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificar_empleadosLayout.createSequentialGroup()
                        .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_modificar_empleadosLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edad_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salario_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_modificar_empleadosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nombre_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificar_empleadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jd_modificar_empleadosLayout.setVerticalGroup(
            jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_empleadosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nombre_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(id_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(edad_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(salario_empleado_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificar_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jLabel15.setText("Nombre");

        jLabel16.setText("Descripcion");

        jLabel17.setText("Marca");

        jLabel18.setText("Numero de Serie");

        guardar_material.setText("Guardar");

        javax.swing.GroupLayout jd_modificar_materialLayout = new javax.swing.GroupLayout(jd_modificar_material.getContentPane());
        jd_modificar_material.getContentPane().setLayout(jd_modificar_materialLayout);
        jd_modificar_materialLayout.setHorizontalGroup(
            jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_materialLayout.createSequentialGroup()
                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificar_materialLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_modificar_materialLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(serie_material_modificar))
                            .addGroup(jd_modificar_materialLayout.createSequentialGroup()
                                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(44, 44, 44)
                                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombre_material_modificar)
                                    .addComponent(descripcion_material_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(marca_material_modificar)))))
                    .addGroup(jd_modificar_materialLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(guardar_material)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jd_modificar_materialLayout.setVerticalGroup(
            jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_materialLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nombre_material_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(descripcion_material_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(marca_material_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_modificar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(serie_material_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(guardar_material)
                .addGap(32, 32, 32))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRUMP TOWER ©");

        jTabbedPane1.setToolTipText("");

        jPanel1.setToolTipText("");

        jLabel1.setText("Nombre");

        jLabel2.setText("ID");

        jLabel3.setText("Edad");

        jLabel4.setText("Direccion");

        jLabel5.setText("Salario");

        direccion_empleado.setColumns(20);
        direccion_empleado.setRows(5);
        jScrollPane1.setViewportView(direccion_empleado);

        jButton1.setText("AGREGAR");
        jButton1.setToolTipText("Da click para agregar un empleado");
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("MODIFICAR");
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("ELIMINAR");
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(edad_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salario_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lista_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edad_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salario_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lista_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empleados", jPanel1);

        tabla_materiales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Marca", "Numero de Serie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla_materiales);

        jLabel11.setText("Nombre");

        jLabel12.setText("Descripcion");

        jLabel13.setText("Marca");

        jLabel14.setText("Numero de Serie");

        bt_agregar_material.setText("Agregar");
        bt_agregar_material.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt_agregar_materialMouseMoved(evt);
            }
        });
        bt_agregar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_materialMouseClicked(evt);
            }
        });

        bt_modificar_material.setText("Modificar");
        bt_modificar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificar_materialMouseClicked(evt);
            }
        });

        bt_eliminar_material.setText("Eliminar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serie_material, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(marca_material, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addComponent(nombre_material)
                                .addComponent(descripcion_material))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(bt_agregar_material)))
                .addGap(218, 218, 218))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_modificar_material)
                .addGap(18, 18, 18)
                .addComponent(bt_eliminar_material)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nombre_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(descripcion_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(marca_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(serie_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_agregar_material)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_modificar_material)
                    .addComponent(bt_eliminar_material))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Materiales", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Productos", jPanel3);

        jl_hora.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jl_hora.setForeground(new java.awt.Color(214, 27, 58));
        jl_hora.setText("0");

        titulo_cronometro.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        titulo_cronometro.setText("Tiempo total de operacion:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(titulo_cronometro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(176, 176, 176))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jl_hora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulo_cronometro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_hora)
                .addContainerGap(371, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ordenes", jPanel4);

        jButton5.setText("SALIR");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Empleados temp = (Empleados) lista_empleados.getSelectedItem();
        nombre_empleado_m.setText(temp.getNombre());
        id_empleado_m.setText(Integer.toString(temp.getID()));
        edad_empleado_m.setText(Integer.toString(temp.getEdad()));
        salario_empleado_m.setText(Integer.toString(temp.getSalario()));
        direccion_empleado_m.setText(temp.getDireccion());

        jd_modificar_empleados.setModal(true);
        jd_modificar_empleados.pack();
        jd_modificar_empleados.setLocationRelativeTo(this);
        jd_modificar_empleados.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void bt_modificar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificar_materialMouseClicked
        jd_modificar_material.pack();
        jd_modificar_material.setModal(true);
        jd_modificar_material.setLocationRelativeTo(this);
        jd_modificar_material.setVisible(true);
    }//GEN-LAST:event_bt_modificar_materialMouseClicked

    private void bt_agregar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_materialMouseClicked

        if (bt_agregar_material.isEnabled()) {
            String nombre, descripcion, marca;
            int id;
            nombre = nombre_material.getText();
            descripcion = descripcion_material.getText();
            marca = marca_material.getText();
            id = Integer.parseInt(serie_material.getText());

            nombre_material.setText("");
            descripcion_material.setText("");
            marca_material.setText("");
            serie_material.setText("");
            boolean repetido = false;
            for (int i = 0; i < catalogo.size(); i++) {
                if ((((Materiales) catalogo.at(i)).nombre).equals(nombre) && (((Materiales) catalogo.at(i)).marca).equals(marca)) {
                    repetido = true;
                }
            }
            if (!repetido) {
                catalogo.push_back(new Materiales(nombre, descripcion, marca, id));
                DefaultTableModel a = (DefaultTableModel) tabla_materiales.getModel();
                String[] row = {nombre, descripcion, marca, Integer.toString(id)};
                a.addRow(row);

                JOptionPane.showMessageDialog(this, "Material Agregado");
            } else {
                JOptionPane.showMessageDialog(this, "Ese material ya se encuentra en el catalogo");
            }
        }

    }//GEN-LAST:event_bt_agregar_materialMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (jButton1.isEnabled()) {
            String Nombre, Direccion;
            int ID, Edad, Salario;
            boolean Agregar = true;

            Nombre = nombre_empleado.getText();
            Direccion = direccion_empleado.getText();
            ID = Integer.parseInt(id_empleado.getText());
            Edad = Integer.parseInt(edad_empleado.getText());
            Salario = Integer.parseInt(salario_empleado.getText());

            Empleados nuevo_empleado = new Empleados(Nombre, ID, Edad, Direccion, Salario);
            for (int i = 0; i < lista_empleados.getItemCount(); i++) {
                if (((((Empleados) (lista_empleados.getItemAt(i))).getNombre()).toLowerCase()).equals(Nombre.toLowerCase())) {
                    Agregar = false;
                }
            }

            if (Agregar) {
                empleados.Queue(nuevo_empleado);
                lista_empleados.addItem(nuevo_empleado);
                lista_empleados_temp.push_back(nuevo_empleado);
                JOptionPane.showMessageDialog(this, "Ha agregado un empleado",
                        "AGREGAR EMPLEADOS", JOptionPane.INFORMATION_MESSAGE);

                nombre_empleado.setText("");
                direccion_empleado.setText("");
                id_empleado.setText("");
                edad_empleado.setText("");
                salario_empleado.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Esta agregando un empleado ya existente",
                        "AGREGAR EMPLEADOS", JOptionPane.INFORMATION_MESSAGE);

                nombre_empleado.setText("");
            }

        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        if ((nombre_empleado.getText()).equals("") || (id_empleado.getText()).equals("")
                || (edad_empleado.getText()).equals("") || (salario_empleado.getText()).equals("")
                || (direccion_empleado.getText()).equals("")) {

            jButton1.setEnabled(false);
        } else {
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1MouseMoved

    private void bt_agregar_materialMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_materialMouseMoved
        if ((nombre_material.getText()).equals("") || (descripcion_material.getText()).equals("")
                || (serie_material.getText()).equals("") || (marca_material.getText()).equals("")) {

            bt_agregar_material.setEnabled(false);
        } else {
            bt_agregar_material.setEnabled(true);
        }
    }//GEN-LAST:event_bt_agregar_materialMouseMoved

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved
        // TODO add your handling code here:
        if ((nombre_empleado_m.getText()).equals("") || (id_empleado_m.getText()).equals("")
                || (edad_empleado_m.getText()).equals("") || (salario_empleado_m.getText()).equals("")
                || (direccion_empleado_m.getText()).equals("")) {

            jButton4.setEnabled(false);
        } else {
            jButton4.setEnabled(true);
        }
    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        if (jButton4.isEnabled()) {
            Empleados temp = (Empleados) lista_empleados.getSelectedItem();

            temp.setNombre(nombre_empleado_m.getText());
            temp.setID(Integer.parseInt(id_empleado_m.getText()));
            temp.setEdad(Integer.parseInt(edad_empleado_m.getText()));
            temp.setSalario(Integer.parseInt(salario_empleado_m.getText()));
            temp.setDireccion(direccion_empleado_m.getText());

            nombre_empleado_m.setText("");
            id_empleado_m.setText("");
            edad_empleado_m.setText("");
            salario_empleado_m.setText("");
            direccion_empleado_m.setText("");
            
            jd_modificar_empleados.setVisible(false);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        // TODO add your handling code here:
        if (lista_empleados.getItemCount() == 0) {
            jButton2.setEnabled(false);
        } else {
            jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        // TODO add your handling code here:
        if (lista_empleados.getItemCount() == 0) {
            jButton3.setEnabled(false);
        } else {
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        lista_empleados_temp.erase(lista_empleados.getSelectedIndex() - 1);
        lista_empleados.removeAllItems();
        
        while(empleados.GetSize() != 0){
          empleados.DeQueue();  
        }     

        for (int i = 0; i < lista_empleados_temp.size(); i++) {
            lista_empleados.addItem(lista_empleados_temp.at(i));
        }
        
        for (int i = 0; i < lista_empleados_temp.size(); i++) {
            empleados.Queue((Empleados)lista_empleados_temp.at(i));
        }


    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DTrump.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DTrump.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DTrump.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DTrump.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DTrump().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregar_material;
    private javax.swing.JButton bt_eliminar_material;
    private javax.swing.JButton bt_modificar_material;
    private javax.swing.JTextField descripcion_material;
    private javax.swing.JTextField descripcion_material_modificar;
    private javax.swing.JTextArea direccion_empleado;
    private javax.swing.JTextArea direccion_empleado_m;
    private javax.swing.JTextField edad_empleado;
    private javax.swing.JTextField edad_empleado_m;
    private javax.swing.JButton guardar_material;
    private javax.swing.JTextField id_empleado;
    private javax.swing.JTextField id_empleado_m;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jd_modificar_empleados;
    private javax.swing.JDialog jd_modificar_material;
    private javax.swing.JLabel jl_hora;
    private javax.swing.JComboBox<Object> lista_empleados;
    private javax.swing.JTextField marca_material;
    private javax.swing.JTextField marca_material_modificar;
    private javax.swing.JTextField nombre_empleado;
    private javax.swing.JTextField nombre_empleado_m;
    private javax.swing.JTextField nombre_material;
    private javax.swing.JTextField nombre_material_modificar;
    private javax.swing.JTextField salario_empleado;
    private javax.swing.JTextField salario_empleado_m;
    private javax.swing.JTextField serie_material;
    private javax.swing.JTextField serie_material_modificar;
    private javax.swing.JTable tabla_materiales;
    private javax.swing.JLabel titulo_cronometro;
    // End of variables declaration//GEN-END:variables
    Lista catalogo = new Lista();
    Cola_Empleados empleados = new Cola_Empleados();
    Lista lista_empleados_temp = new Lista();
}
